backend:
  name: github
  repo: mkozhukharenko/phenomic-example
  branch: master # replace if you want netlify-cms publish on a different branch

media_folder: "content/assets" # Folder where user uploaded files should go

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts" # a subfolder of your public_folder
    create: true
    card: {type: "alltype", text: "title"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "settings"
      label: "Settings"
      files:
        - name: "general"
          label: "General settings"
          file: "_settings/general.json"
          fields:
            - {label: "Main site title", name: "site_title", widget: "string"}
            - {label: "Number of fronpage posts", name: "post_count", widget: "number"}
            - {label: "Site cover image", name: "cover", widget: "image"}
